site_name: Comers Documentation
site_description: "Comers Documentation"
site_author: ""
site_url: ""
strict: false
# repo_name: "docs-comers"
# repo_url: "https://github.com/begabba/docs-comers/"

theme:
  name: "material"
  custom_dir: overrides
  language: "en"
  palette:
    primary: "Blue grey"
    accent: "Blue grey"
  font:
    text: "Roboto"
    code: "Roboto Mono"
  logo: "images/logo.svg"
markdown_extensions:
  - tables
  - admonition
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
plugins:
  - search:
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # offical plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/diagrams" # should reside under docs_dir
      output_folder: "out"
      input_folder: "src"
      input_extensions: "" # comma separated list of extensions to parse, by default every file is parsed
#       guess_lang: false
