site_name: Comers Documentation
site_description: "Comers Documentation"
site_author: "Erik"
site_url: ""
strict: false

repo_name: "docs-comers"
repo_url: "https://github.com/gitx-xx/docs-comers/"
# copyright: 'Copyright &copy; 2020'

theme:
  name: "material"
  custom_dir: overrides
  language: "en"
  palette:
    primary: "Blue grey"
    accent: "Blue grey"
  font:
    text: "Roboto"
    code: "Roboto Mono"

  logo: "images/logo.svg"
extra_css:
  - "stylesheets/extra.css"
markdown_extensions:
  - admonition
  - toc:
      permalink: true
#   - codehilite:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
  - search:
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/local/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # offical plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/diagrams" # should reside under docs_dir
      output_folder: "out"
      input_folder: "src"
      input_extensions: "" # comma separated list of extensions to parse, by default every file is parsed
#       guess_lang: false
